# Generated by Django 5.1.6 on 2025-02-14 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('guards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comments', models.TextField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guards.securityguard')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
    ]
