# Generated by Django 5.1.6 on 2025-02-14 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('guards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='guard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guards.securityguard'),
        ),
    ]
