# Generated by Django 5.1.6 on 2025-02-14 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past_experience', models.TextField(blank=True, max_length=500, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('M', 'N')], default='Morning', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('work_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guard.workdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('work_detail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guard.workdetail')),
            ],
        ),
    ]
