# Generated by Django 5.1.6 on 2025-02-14 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='relationship',
        ),
    ]
